/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latitude.coding.challenge;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.BeforeEach;

import java.util.stream.IntStream;

public class AppTest {
	public static final int TRADING_TIME_IN_MINUTES = 360;
	int[] stockPrices;
	
	@BeforeEach
	public void setUp()
	{
	}
    @Test 
	public void stockCalculator_returnsBestProfit() {
		stockPrices = new int[]{10, 7, 5, 8, 11, 9};
		assertEquals (6, App.getMaxProfit(stockPrices)); // returns 6 (buy at $5 sell)
    }
	@Test
	public void stockCalculator_shouldReturnZero_When_ArrayInputLength_IsLessThan_Two()
	{
		stockPrices = new int[]{0};
		assertEquals(0, App.getMaxProfit(stockPrices));
	}
	@Test
	public void stockCalculator_should_only_operate_within_trading_hours()
	{
		int minutesToAdd = 60;
		stockPrices = IntStream.rangeClosed(0, App.TRADING_TIME_IN_MINUTES + minutesToAdd).toArray();
		assertEquals(TRADING_TIME_IN_MINUTES, App.getMaxProfit(stockPrices));
	}
}
