/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latitude.coding.challenge;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

public class AppTest {
    @Test 
	@DisplayName("Test that addition works")
	public void testAddition() {
		assertEquals(2 + 2, 4, "2 + 2 should equal 4");
    }
}
