/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latitude.coding.challenge;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.Test;

import java.util.stream.IntStream;

public class StockProfitCalculatorTest {
	public static final int TRADING_TIME_IN_MINUTES = 360;
	int[] stockPrices;
	
    @Test 
	public void stockCalculator_returnsBestProfit() {
		stockPrices = new int[]{10, 7, 5, 8, 11, 9};
		assertEquals (6, StockProfitCalculator.getMaxProfit(stockPrices)); // returns 6 (buy at $5 sell)
    }
	@Test
	public void stockCalculator_shouldReturnZero_When_ArrayInputLength_IsLessThan_Two()
	{
		stockPrices = new int[]{0};
		assertEquals(0, StockProfitCalculator.getMaxProfit(stockPrices));
	}
	@Test
	public void stockCalculator_throwsException_whenGivenInputArray_thatIsTooLarge()
	{
		int minutesToAdd = 60;
		stockPrices = IntStream.rangeClosed(0, StockProfitCalculator.TRADING_TIME_IN_MINUTES + minutesToAdd).toArray();
		

		Exception exception = assertThrows(IllegalArgumentException.class, () -> {
				StockProfitCalculator.getMaxProfit(stockPrices);
		});

		String expectedExceptionMessage = "Stock Prices input length of " + stockPrices.length + " exceeded maximum length of " + TRADING_TIME_IN_MINUTES;
		String actualExceptionMessage = exception.getMessage();
		assertEquals(expectedExceptionMessage, actualExceptionMessage);
	}
}
